import Head from 'next/head';
// import Image from 'next/image';
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-Primary-light bg-[url('/bg-pattern-intro-mobile.svg')] bg-[length:250%_250%] bg-center overflow-hidden relative rounded-bl-[80px] ">
        <Header />
      </header>
      <main>
        <h1>hello</h1>
      </main>

      <footer></footer>
    </div>
  );
}
