import React from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import PartTwo from '../components/PartTwo';
import PartOne from '../components/PartOne';
import PartThree from '../components/PartThree';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-Primary-light bg-[url('/bg-pattern-intro-mobile.svg')] sm:bg-[url('/bg-pattern-intro-desktop.svg')] bg-[length:250%] bg-center overflow-hidden relative rounded-bl-[80px] mb-8">
        <Header />
      </header>
      <main className="overflow-clip">
        <PartOne />
        <PartTwo />
        <PartThree />
      </main>

      <footer className="bg-Neutral-darkBlackBlue rounded-tr-[80px] ">
        <Footer />
      </footer>
    </div>
  );
}
